### ISSUE TITLE
Fix par/layout override on glmtools plotting functions (e.g. summarize_sim fails)

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/glmtools#110]
From here
https://github.com/GLEON/GLMr/issues/56

```R
library(glmtools)
sim_folder <- system.file('extdata/v2.0.0sim', package = 'GLMr')
run_glm(sim_folder)
out_file <- file.path(sim_folder,'output.nc')
nml_file <- system.file('extdata/v2.0.0sim', 'glm2.nml', package = 'GLMr')
field_file <- system.file('extdata', 'field_data.tsv', package = 'GLMr')
plot_temp(file = out_file, fig_path = 'test_temp.png')
summarize_sim(out_file, sim_outputs = c('temp','surface_height','wind'))
````

gives funky plotting issues. glmtools bug? I think so

**Comment by jread-usgs** [comment]
http://seananderson.ca/courses/11-multipanel/multipanel.pdf

**Comment by jread-usgs** [comment]
things that plot:
- [ ] `summarize_sim`
- [ ] `plot_var`
- [ ] `plot_temp`
- [ ] `plot_compare_stage`
- [ ] `plot_temp_compare`
- [ ] `plot_validate_profiles`
- [ ] `validate_sim`

**Comment by jread-usgs** [comment]
@lawinslow personally, I would like to wipe out some bloat now that get_var and plot_var exist. Replace summarize_sim with plot_var? (plot_var could take a vector of var_names instead of just one). Also, is `validate_sim` redundant with some of the other `compare` plots?
