### ISSUE TITLE
scope glmtools examples and package data relative to GLMr

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/glmtools#118]
glmtools contains:
 - driver data
 - calibration data
 - `run_example_sim()` function (which builds glm2.nml in temp dir, moves driver and runs model)

**Comment by jread-usgs** [comment]
@lawinslow so...
The way I am seeing it is that neither package actually contains a .nc or lake.csv etc. Did I miss anything?

**Comment by lawinslow** [comment]
Nope. Those outputs are generated from the inputs, no need to store them. Looking good

**Comment by jread-usgs** [comment]
- [ ] `compare_to_field()`
- [ ] `plot_temp_compare()`
- [ ] `plot_temp()`
- [ ] `plot_var()`
- [ ] `summarize_sim()`
- [ ] `plot_temp_compare`
- [ ] `sim_vars()`
- [ ] `resample_to_field()`
- [ ] `get_temp()`
- [ ] `plot_validate_profiles()`

**Comment by jread-usgs** [comment]
I think this list is complete..
Makes me not want to do this again.

**Comment by jread-usgs** [comment]
Also accomplished w/ #120
