### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by hdugan** [USGS-R/glmtools#132]
I keep getting this error on installation (on MacOS): 

``Error in library(glmtools) : there is no package called ‘glmtools’
Calls: .First -> library
Execution halted``
``Warning in install.packages :
  installation of package ‘GLMr’ had non-zero exit status``

``Error in library(glmtools) : there is no package called ‘glmtools’
Calls: .First -> library
Execution halted``
``Warning in install.packages :
  installation of package ‘glmtools’ had non-zero exit status``

**Comment by jread-usgs** [comment]
I think this is an issue with where the different packages are hosted. Can you past in the code you used to install the package?

**Comment by hdugan** [comment]
From the github page...

``install.packages("glmtools", 
    repos = c("http://gleon.github.com/", "http://usgs-r.github.com/", "http://cran.us.r-project.org"),
    dependencies = TRUE,
    type = "both")``

**Comment by jread-usgs** [comment]
We did something silly. I will fix it and modify the install instructions after Luke posts the packages

**Comment by lawinslow** [comment]
Ok, Fixed. Both GLMr and glmtools are now available from GRAN. Install instructions [here](http://owi.usgs.gov/R/gran.html). Let us know how that goes.

**Comment by hdugan** [comment]
GRAN!!! Cool. 

Warning in install.packages :
  unable to access index for repository http://owi.usgs.gov/R/bin/macosx/contrib/3.0

   package ‘glmtools’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘glmtools’ is not available (for R version 3.0.3)

**Comment by jread-usgs** [comment]
@hdugan upgrade R!!

**Comment by hdugan** [comment]
Done. Although I'll miss seeing "warm puppy" as my build. 
However, 
``
   package ‘glmtools’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘glmtools’ is not available (for R version 3.1.2)``

**Comment by jread-usgs** [comment]
ok, I guess the mac binaries aren't up yet. just add `type='both'` to your `install.packages` arguments

**Comment by hdugan** [comment]
Halfway. This installed GLMr:
``install.packages("glmtools", repos="http://owi.usgs.gov/R",type='both')``

But not glmtools:
``Error in library(glmtools) : there is no package called ‘glmtools’
Calls: .First -> library
Execution halted
Warning in install.packages :
  installation of package ‘glmtools’ had non-zero exit status``

**Comment by jread-usgs** [comment]
`install.packages("glmtools", repos="http://owi.usgs.gov/R",type='both', dependencies = TRUE)`

**Comment by hdugan** [comment]
Same result

**Comment by jread-usgs** [comment]
@lawinslow it sure doesn't look like `glmtools` is on GRAN.

**Comment by lawinslow** [comment]
LaMeO. Looking into it.

**Comment by lawinslow** [comment]
@hdugan should be fixed now. Give it another go.

**Comment by hdugan** [comment]
Still same error.

**Comment by lawinslow** [comment]
Have you restarted R since you last tried? If not, could you restart it and give this a go

    install.packages("glmtools", repos="http://owi.usgs.gov/R")

**Comment by hdugan** [comment]
I thought so... but success! GLM forever!

**Comment by jread-usgs** [comment]
woot woot!
