### ISSUE TITLE
file argument default

### ISSUE THREAD

**Issue by hdugan** [USGS-R/glmtools#148]
It would be cool if the file argument defaulted to 'output.nc' for functions such as:
sim_var(file='output.nc')
plot_var(file='output.nc',...)

**Comment by jread-usgs** [comment]
I agree w/ this. Any reason not to implement @lawinslow ?

@hdugan up for a pull request?

**Comment by lawinslow** [comment]
Nope, no reason not to. Go for it @hdugan
