### ISSUE TITLE
create "block off" or something to comment or remove a block of nml

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/glmtools#156]
function to easily turn off (for example) aed part of the sim

**Comment by lawinslow** [comment]
@dzrobert upvotes this

**Comment by jread-usgs** [comment]
@lawinslow got any suggestions for the syntax on this? I think I can implement it (and will self-assign), but should this be an arg in `set_nml`, or a different function?

**Comment by lawinslow** [comment]
No clue, would we be able to turn it back on? If not, it seems you'd just need a `rm_nml_block` or something function. Otherwise, toggle or enable/disable would be nice functionality.

**Comment by jread-usgs** [comment]
the complexity of this wildly varies depending on whether we want "switch off" vs "toggle on/off". If it is a toggle, it is kind of more in-line with the support of comments in #139

**Comment by lawinslow** [comment]
Yeah, I know. @dzrobert, would just `rm_nml_block` be helpful? Or do you want to toggle it on and off?

**Comment by jread-usgs** [comment]
@hdugan did you have a use-case for this, or does it not apply to your workflow?

**Comment by jread-usgs** [comment]
@lawinslow I think I may add the `rm_nml_block` and then a quick `add_nml_block` that accepts a list of depth = 1. To get fancy, the return of `rm_nml_block` could be an invisible list of that block that was removed, so if you wanted to toggle:
```R
aed_block <- rm_nml_block(glm_nml, `wq_setup`)
#...write glm etc
# run sim w/ aed off
add_nml_block(glm_nml, aed_block)
# run sim w/ aed off
```

ugg, nevermind, that won't work w/ pass by copy.

Other ideas to support a toggle without a major overhaul?

**Comment by lawinslow** [comment]
Ok, how about this

```
#this gets a block
cached_block = glm_nml['&wq_setup'] 

#this sets a new block or overwrites one with that name
glm_nml['&wq_2_setup'] = cached_block

#this removes a block
glm_nml['&wq_setup'] = NULL

#this gets a value for a variable in a specific block (supporting AED files)
glm_nml['&wq_setup/variable']

#this sets that variable inside the block
glm_nml['&wq_setup/variable'] = newvalue

#this works just like get_nml_value
glm_nml['variable']

#This works jus tlike set_nml
glm_nml['variable'] = 'some new value'
```

Thoughts?

**Comment by jread-usgs** [comment]
I like this a lot. 

Personally, I do like going with 
`glm_nml['&wq_setup::variable'] = newvalue`
to follow R's hierarchy for package::function, instead of treating it like xpath. I would like to converge on something though, because I am using something similar in `geoknife` to do quick feature grabs (`webgeom('state::NH')` for the state of New Hampshire; similar for ecoregions, etc.) I would like to have consistency w/ this too.

**Comment by jread-usgs** [comment]
Curious though, @lawinslow - is this kind of thing possible with the `[` generic?
```R
glm_nml['variable','variable_2'] = c('some new value','other new value')
```

**Comment by lawinslow** [comment]
It would be possible, but maybe not desirable given the conflation of dimensionality.

How about 
```
glm_nml[c('variable','variable_2')] = c('some new value','other new value')
```

**Comment by jread-usgs** [comment]
yes, that works for me

**Comment by jread-usgs** [comment]
Closing for #255
