### ISSUE TITLE
generalized comparison plot

### ISSUE THREAD

**Issue by snortheim** [USGS-R/glmtools#159]

**Comment by jread-usgs** [comment]
@snortheim so like a `plot_compare_var` function?

**Comment by jread-usgs** [comment]
working on this now, but only for DO since the unit conversions are so tricky for the state variables

**Comment by jread-usgs** [comment]
Would be something like this
![image](https://cloud.githubusercontent.com/assets/2349007/9935346/a84cd346-5d1b-11e5-8cf2-62d38156a5d9.png)

but, depth on the y-axis, w/ a general colorbar

**Comment by jread-usgs** [comment]
`plot_temp_compare()` will now call `plot_var_compare()` with `var_name='temp'`

**Comment by dzrobert** [comment]
Hi Jordan,
 That is exactly what I am thinking, just for Dissolved Oxygen.

Thanks,
Dale

On Thu, Sep 17, 2015 at 9:08 AM, Jordan S Read <notifications@github.com>
wrote:

> Would be something like this
> [image: image]
> <https://cloud.githubusercontent.com/assets/2349007/9935346/a84cd346-5d1b-11e5-8cf2-62d38156a5d9.png>
>
> but, depth on the y-axis, w/ a general colorbar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/glmtools/issues/159#issuecomment-141098283>.
>



-- 
Dale M. Robertson, PhD
Research Hydrologist                    Telephone # 608-821-3867
U.S. Geological Survey                  Fax #              608-821-3817
Water Science Center                   Email Address: dzrobert@usgs.gov
8505 Research Way                      Office Web Site: wi.water.usgs.gov
Middleton, WI 53562
Personal Web Site: wi.water.usgs.gov/professional-pages/robertson.html

**Comment by jread-usgs** [comment]
Question for the group. In general, should Modeled be on top and Observed be on bottom? @dzrobert

**Comment by jread-usgs** [comment]
current plots:
![image](https://cloud.githubusercontent.com/assets/2349007/9941132/e6e48820-5d38-11e5-928a-a2530d5b5cd4.png)

**Comment by eread-usgs** [comment]
@jread-usgs @dzrobert I think the way it is shown, with observed on top and modeled on the bottom, is a good way to do it.

**Comment by jread-usgs** [comment]
OK, we'll stick with that unless I hear objections.

**Comment by jread-usgs** [comment]
Also, another thing to note here is that the `modeled` is sampled to match the time points sampled in `observed` (so it is artificially coarser in time than the actual sim). This is different than the way it was done in the past, where the model plot was daily for the duration of the model run (see earlier fig up top). Issues with this?

**Comment by jread-usgs** [comment]
@eread-usgs suggests the obs re-sampling should be an argument

**Comment by jread-usgs** [comment]
I think this is done as it exists in `plot_var_compare()`
