### ISSUE TITLE
plot_temp field data? 

### ISSUE THREAD

**Issue by hdugan** [USGS-R/glmtools#172]
For plot_temp_compare, the field data .csv/.tsv is structured as data.frame(datetime,depth,wtemp). 

Can a heatmap of water temp be made for just field data? As opposed to using rlakeanalyzer, which requires more of a matrix form for data with unique depths as columns?

**Comment by jread-usgs** [comment]
I would :+1: that. I think the pieces might be there internally

**Comment by jread-usgs** [comment]
but would require a bit of work. probably not too bad

**Comment by lawinslow** [comment]
Yeah, shouldn't be hard. `plot_var_field`? `plot_field_var`?

Alternative would be to make read.ts in rLakeAnalyzer more general so it can read in either wide format, or long format and pivot it into a wide format. Do you want to be able to handle just manually observed data or profiler data as well? @jabrent might have an example set of code for doing the pivoting.

**Comment by jabrent** [comment]
Yep, I definitely have some code for doing some pivoting. The reshape2 package is really helpful and this page: http://seananderson.ca/2013/10/19/reshape.html has some good info for how to set the fields for dcast if you want to get from long to wide format data. melt let's you go the other way.
#Chl Reshape
Chl_profile = read.csv("Chl_Reshape_Oct2014.csv") #the structure of this data is for multiple profiles and is a column of datetime, a column of depth, and a column of the actual data chl in this case
Chl.pivoted = dcast(Chl_profile, DateTime_hh~Depth_m,mean,value.var="chlF_RFU") #this puts depth along the first row with each depth in their own column and date time in the first column with each profile in a row. let me know if you want any data examples. what does your field data look like?

**Comment by jread-usgs** [comment]
With the more generic title `rLakeAnalyzer`, it might be good to outsource some plotting from there for the manual stuff...hmm

**Comment by jread-usgs** [comment]
So, question for the group - how much plotting should be done in `rLakeAnalyzer` vs this package?

**Comment by jread-usgs** [comment]
@hdugan was this covered in your plotting overhaul?

**Comment by hdugan** [comment]
yes. with `plot_var_df`
