### ISSUE TITLE
plot_temp_compare() in NYC reservoirs

### ISSUE THREAD

**Issue by TomLeeyuli** [USGS-R/glmtools#183]
When I use plot_temp_compare () to plot temperature variable in NYC reservoirs, I have got a weird result (attached). It seems the the reservoir water surface at the bottom.  May I ask you what I should do to correct the plot_temp_compare () result?
![temperature](https://cloud.githubusercontent.com/assets/11527792/11005081/cbdd2690-8489-11e5-8cb8-f1551307546d.png)

**Comment by jread-usgs** [comment]
plot times not the same...

**Comment by TomLeeyuli** [comment]
Yes, you are right. When I use plot_temp_compare(), it produces the x-axis in different times. This is another problem.

**Comment by jread-usgs** [comment]
what version of glmtools are you using?

**Comment by TomLeeyuli** [comment]
Documentation for package ‘glmtools’ version 0.10.1

**Comment by jread-usgs** [comment]
Can you update to the current version (0.10.2) and paste your figure in here? It may not change, but I want to make sure we are starting from the same version of the package.

**Comment by TomLeeyuli** [comment]
OK!

**Comment by lawinslow** [comment]
Cleaning up old issues. Re-open if still an issue.
