### ISSUE TITLE
Is the gap between the near-surface points and heatmap valid?

### ISSUE THREAD

**Issue by lawinslow** [USGS-R/glmtools#192]
See the dots on the top. Looks worse with other data. 

![image](https://cloud.githubusercontent.com/assets/347600/12650437/78261830-c5a8-11e5-8e77-d7550d432582.png)

**Comment by lawinslow** [comment]
Actually, bottom point is most obvious here. Weird.

**Comment by jread-usgs** [comment]
@lawinslow did you want to take this on, or tag as help wanted?

**Comment by lawinslow** [comment]
Answer was nope. Fixed.
