### ISSUE TITLE
changing scale on heat map (thermal profile through time)

### ISSUE THREAD

**Issue by KRChristianson** [USGS-R/glmtools#195]
I am trying to compare heat maps of different waters, however, the thermal scale of varying colors changes from map to map, making it difficult to make comparisons. Any ideas on how to be able to set a color scale?

**Comment by jread-usgs** [comment]
I like this idea, and I think it should be supported. 

I would suggest adding an additional argument to the heatmap functions that lets you pass in a range. Right now I think you can specify a palette, but the range is auto-calculated, which is a bit limiting.

**Comment by jread-usgs** [comment]
working on a pull request for this. But it is just for `plot_temp_compare` `and plot_var_compare` for now. Are you using `plot_var`?

![image](https://cloud.githubusercontent.com/assets/2349007/13747954/b0029abe-e9c8-11e5-948e-19e256cad721.png)

### Syntax
```r
sim_folder <- run_example_sim(verbose = FALSE)
nc_file <- file.path(sim_folder, 'output.nc')
nml_file <- file.path(sim_folder, 'glm2.nml')
field_file <- file.path(sim_folder, 'field_data.tsv')

plot_temp_compare(nc_file, field_file, fig_path='test.png', col_lim=c(3.5,35))
```

This will lock the color range to 3.5-35°C

**Comment by KRChristianson** [comment]
Thanks.
I am getting an error that states col_lim is not a graphical parameter

On Mon, Mar 14, 2016 at 9:15 AM, Luke Winslow <notifications@github.com>
wrote:

> Closed #195 <https://github.com/USGS-R/glmtools/issues/195> via e146658
> <https://github.com/USGS-R/glmtools/commit/e146658a917e21b74ed660ebf9cc0662e55921a3>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/glmtools/issues/195#event-588858479>.
>



-- 
*Kyle Christianson*
PhD Student
NSF I-WATER Fellow
Department of Fish, Wildlife and Conservation Biology
1474 Campus Delivery
Colorado State University
Fort Collins, CO 80523-1474
kchrist@rams.colostate.edu
701-361-6790

**Comment by jread-usgs** [comment]
I think you will need to update the package @KRChristianson 

```r
library(devtools)
install_github('USGS-R/glmtools')
```
does that work for you?

**Comment by KRChristianson** [comment]
I received the following error: Error in loadNamespace(j <- i[[1L]],
c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  there is no package called ‘sp’

On Mon, Mar 14, 2016 at 1:45 PM, Jordan S Read <notifications@github.com>
wrote:

> I think you will need to update the package @KRChristianson
> <https://github.com/KRChristianson>
>
> library(devtools)
> install_github('USGS-R/glmtools')
>
> does that work for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/glmtools/issues/195#issuecomment-196493107>.
>



-- 
*Kyle Christianson*
PhD Student
NSF I-WATER Fellow
Department of Fish, Wildlife and Conservation Biology
1474 Campus Delivery
Colorado State University
Fort Collins, CO 80523-1474
kchrist@rams.colostate.edu
701-361-6790

**Comment by jread-usgs** [comment]
You had that error with this command?
```
library(devtools)
install_github('USGS-R/glmtools')
```

if you don't have devtools, can you install it w/ `install.packages('devtools')`?

**Comment by lawinslow** [comment]
I've gotten that before. It's sometimes useful to restart R and force the `sp` package install.

```R
install.packages('sp')
library(devtools)
install_github('USGS-R/glmtools')
```

**Comment by jread-usgs** [comment]
yeah, but `glmtools` doesn't use `sp`, right?

**Comment by KRChristianson** [comment]
That worked! Many thanks! I am still working on learning the workings of
R...

On Mon, Mar 14, 2016 at 2:23 PM, Jordan S Read <notifications@github.com>
wrote:

> yeah, but glmtools doesn't use sp, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-R/glmtools/issues/195#issuecomment-196506900>.
>



-- 
*Kyle Christianson*
PhD Student
NSF I-WATER Fellow
Department of Fish, Wildlife and Conservation Biology
1474 Campus Delivery
Colorado State University
Fort Collins, CO 80523-1474
kchrist@rams.colostate.edu
701-361-6790

**Comment by lawinslow** [comment]
No, but for whatever reason, I've run into that *exact* thing on various packages.

**Comment by jread-usgs** [comment]
weird. Haven't hit that one. Keep us posted as to how that new `col_lim` thing works @KRChristianson
