### ISSUE TITLE
issue with plot_temp losing col_lim

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/glmtools#201]
@lawinslow I wasn't able to reproduce your issue w/ 

```r
sim_folder <- run_example_sim(verbose = FALSE)
nc_file <- file.path(sim_folder, 'output.nc')
plot_temp(file = nc_file,
```
erring due to no col_lim (v 0.13.2). can you check again and post here the code that caused it?

**Comment by lawinslow** [comment]
It was probably just a fluke then. Maybe a weird version I'd installed to test a PR or who knows.
