### ISSUE TITLE
some variable names from nc can't be parsed into depths. causes plotting issues

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/glmtools#210]
This is covered in #209 

but we should either fail w/ a nice error when the name isn't something we can handle w/ the parsing for depth, or allow more names w/ the parsing function. 

Also, need some test(s) for this.

**Comment by lawinslow** [comment]
If we can assume that all variables and depths will be separated by `_` and that no variable name has an underscore in it, then it would be easy to fix parsing depth. Current strategy looks for numeric portion of the header because the old Matlab version didn't have an underscore and instead used 'temp#.#' as the header.

**Comment by jread-usgs** [comment]
No, I don't think we can make that assumption as the default AED DO variable is `"OXY_oxy_0"`

In order to support the legacy format, we could use two different parsers - one if there is an underscore in the headers (simpler on that splits on '_' and takes the last element) and the more complex one that is in place now for headers that don't have '_'. 

What do you think? also, in `glmtools` or `rLakeAnalyzer`?

**Comment by lawinslow** [comment]
Hmm, good point. To just look for the last `_` kinda bothers me, but not necessarily enough to maybe just go with it. Unless we wanted to decide on something completely different to obviate this issue (`:` perhaps?). Alternatively, maybe glmtools and rLA just need a more complete data structure that better captures this nuance and allows for more robust communication across function calls.

**Comment by jread-usgs** [comment]
I would think that within `glmtools`, we could probably make a painless switch to `:` since the parsing/splitting is done internally and I don't think people are writing the sim data.frames to file (maybe I am wrong?) but we should probably continue to support the matlab LA, the `_` delimited too

**Comment by jread-usgs** [comment]
This is maybe more pressing than expected, because some of the existing vars have numerics in them: `SDF_Fsed_ch4` is one example from AED. I am going to rename this issue

**Comment by lawinslow** [comment]
Yeah, so numerics in the names definitely need to be handled. rLA could be updated to handle temp:##.# pretty easily and could be backwards compatible (if have `:`, use it, if have `_`, use that, if none of above, assume `temp##.#`). 

Ok, second thought, `:` is, I think, no-go. being converted to `.` when I try it in data.frame.

**Comment by jread-usgs** [comment]
stick w/ `_`?

**Comment by lawinslow** [comment]
yeah, we have to. We've pretty much got `.` or `_` to work with

**Comment by lawinslow** [comment]
didn't realize the naming was quite so restrictive. Dug into R source, it is. The more you know.

**Comment by jread-usgs** [comment]
want to do it in rLA then?

**Comment by lawinslow** [comment]
Any numeric characters after the *last* `_` are depth. Everything before the last `_` is variable name. If there is no `_`, assume the variable is temp##.#. Sound good? This is as easy as a change to get.offsets in rLA.

**Comment by jread-usgs** [comment]
yep :+1:

**Comment by jread-usgs** [comment]
fixed in https://github.com/GLEON/rLakeAnalyzer/pull/65, but should we up the rLA version requirement in `glmtools`' DESCRIPTION to reflect it? If not, we can close this out.

**Comment by jread-usgs** [comment]
closed via #211
