### ISSUE TITLE
Plot_var reference

### ISSUE THREAD

**Issue by hdugan** [USGS-R/glmtools#214]
In `plot_var` settings, setting `reference='bottom'` flips heat map, but keeps the surface of the lake at 0. Should `reference='bottom'` instead keep the heat map as is, but let the surface elevation fluctuate? 

Example of  `reference='bottom'` 
![image](https://cloud.githubusercontent.com/assets/5639032/18059951/27b0e858-6de1-11e6-8e9b-a6ebad3c2906.png)

**Comment by lawinslow** [comment]
yeah, but I don't think `plot_var` was actually written to plot bottom-reference data well. Hence the issue you see here. It needs to be overhauled a bit to support bottom-reference out of the box.
