### ISSUE TITLE
Problems installing glmtools with R 3.3.2

### ISSUE THREAD

**Issue by hdugan** [USGS-R/glmtools#217]
Hey, 
The newest R release 3.3.2 is out, and we're having trouble installing glmtools. 
Wondering if this is a problem on our end or not. Asking because Julia is using glm for teaching a lab in ~1 hour :) 

Thanks!

**Comment by jread-usgs** [comment]
What is the error? Have you tried installing from source? Is it glmr or glmtools? Am traveling right now but call me and I can help from the road.

**Comment by lawinslow** [comment]
What's the error and platform? Is GLMr installed?

**Comment by hdugan** [comment]
She is running Windows 7 (I think)
R version 3.3.2

`install.packages('glmtools',repos=c('http://owi.usgs.gov/R')`
Error: 
```
"InternetOpenUrl failed: 'An error occurred in the secure channel support"
"package glmtools is not available (for R version 3.3.2)"
```
The error repeats itself a number of times
same error for GLMr

**Comment by hdugan** [comment]
Works fine for me with R 3.3.1 on Windows 7

**Comment by lawinslow** [comment]
Try:
`install.packages('glmtools',repos=c('https://owi.usgs.gov/R')`

**Comment by jhart6** [comment]
That one unfortunately produces the same error.

**Comment by lawinslow** [comment]
Using RStudio?

**Comment by jhart6** [comment]
Yes

**Comment by lawinslow** [comment]
Try this
http://stackoverflow.com/questions/22721819/download-file-fails-in-rstudio

**Comment by jhart6** [comment]
Okay, so I unchecked the internet box, still producing the same error.

**Comment by lawinslow** [comment]
Not sure then. Maybe [downgrade to known working version](https://cran.r-project.org/bin/windows/base/old/) for now. You could also try the devtools install though I suspect that will also fail. 

```
install.packages('devtools')
devtools::install_github('GLEON/GLMr')
devtools::install_github('USGS-R/glmtools')
```

**Comment by jread-usgs** [comment]
@hdugan any resolution here?

**Comment by jread-usgs** [comment]
This works fine for me on mac w/ newest versions of R and RStudio.

**Comment by hdugan** [comment]
@jhart6 what was the final verdict on this?

**Comment by jhart6** [comment]
Thanks for all of your help trying to resolve this so quickly! We still ran into that error all of last week, which eliminated many of the students from being able to run GLM on their personal computers with the latest R release.  Although another one my TA's had success like you, @jread-usgs. So seemed a little hit or miss.  I haven't tried this week. I'm still running 3.3.1 on my macbook.

**Comment by jread-usgs** [comment]
I hope that people were able to work around this. Since R 3.6 is now out, I am going to close this issue. If install issues crop up on more recent versions, I think a new issue should be opened.
