### ISSUE TITLE
read_nml & set_nml with repeated logical values

### ISSUE THREAD

**Issue by hdugan** [USGS-R/glmtools#226]
I'm running a sim where I have 3 outflows. My working glm2.nml setup looks like this:

```
&outflow
   num_outlet = 3
   flt_off_sw = .false.,.false.,.false.
   outl_elvs = 330.86, 311, 350.52
   bsn_len_outl = 996, 837, 4600
   bsn_wid_outl = 433, 363, 2000
   outflow_fl = 'out1.csv','out2.csv','out3.csv'
   outflow_factor = 1, 1, 1
/
```

When I use `read_nml('glm2.nml')`, it reads `flt_off_sw` as a single FALSE value rather than 3. Also, I can't use `set_nml` to write 3 false values. If there is only one false value, as below, GLM crashes. 

```
&outflow
   num_outlet = 3
   flt_off_sw = .false.
   outl_elvs = 330.86, 311, 350.52
   bsn_len_outl = 996, 837, 4600
   bsn_wid_outl = 433, 363, 2000
   outflow_fl = 'out1.csv','out2.csv','out3.csv'
   outflow_factor = 1, 1, 1
/
```
So basically I can't use a workflow which involves reading and writing a `glm2.nml` file when I have multiple outflows.

**Comment by jread-usgs** [comment]
that's no good @hdugan ... Bummer. I was not considering the case where there would be multiple booleans. 

Would you mind emailing me your nml file so I can give it a shot?

**Comment by hdugan** [comment]
On it's way!

**Comment by jread-usgs** [comment]
@hdugan I can't get to this quite yet, but a workaround for the time being:

```r
nml <- read_nml('.../glm2.nml')
nml$outflow$flt_off_sw <- c('.false.', '.false.', '.false.')
nml
...
&outflow
   num_outlet = 3
   flt_off_sw = .false., .false., .false.
   outl_elvs = 330.86, 311, 350.52
   bsn_len_outl = 996, 837, 4600
   bsn_wid_outl = 433, 363, 2000
   outflow_fl = 'Cannonsville_outflow_withdraw.csv','Cannonsville_outflow_damrelease.csv','Cannonsville_outflow_spill.csv'
   outflow_factor = 1, 1, 1
/
```
is that helpful as a bandaid?

**Comment by hdugan** [comment]
That's incredibly helpful! Thanks @jread-usgs

**Comment by jread-usgs** [comment]
I still plan on working up a fix, but am traveling this week.

**Comment by jread-usgs** [comment]
#227
