### ISSUE TITLE
Package cleanup

### ISSUE THREAD

**Issue by jsta** [USGS-R/glmtools#228]
I plan on submitting a PR with changes similar to those discussed at:
https://github.com/GLEON/GLMr/issues/113

**Comment by jsta** [comment]
One thing I notice right away is that very few (none?) of the examples are set to `dontrun`. This makes running `devtools::check()` very slow. What do think about setting `dontrun` on some of them?

**Comment by lawinslow** [comment]
But having them run means they actually act as a verification that the package is not broken.

**Comment by jsta** [comment]
Hmm, I wonder if there is a way to make things faster then without `dontrun`. I notice that all of the examples have the line:

`sim_folder <- run_example_sim(verbose = FALSE)`

Maybe moving package verification to `tests` would allow this line to be run only once (or at least fewer times) during checking?

**Comment by lawinslow** [comment]
I have no issue moving things into testthat, but @jread-usgs is jury and judge for this package, so it's primarily up to him

**Comment by jsta** [comment]
I found out that the following command will run `check` without executing the examples:

```
devtools::check(args = "--no-examples")
```
