### ISSUE TITLE
plot_meteo paths 

### ISSUE THREAD

**Issue by wdwatkins** [USGS-R/glmtools#235]
Something weird seems to be happening with the path created:
![image](https://user-images.githubusercontent.com/13987349/27356673-fee5759c-55d4-11e7-83d2-07bb33aa3913.png)
It is appending the temp directory path to the argument given.

**Comment by jread-usgs** [comment]
In the new version, this function points to the met file itself, not the nml file, so I'm closing this issue as it is no longer an issue
