### ISSUE TITLE
Change the color palette of the heat map

### ISSUE THREAD

**Issue by dvalenciaca** [USGS-R/glmtools#239]
The owner of this repository, @jread-usgs wrote in a comment

> I like this idea, and I think it should be supported.
> 
> I would suggest adding an additional argument to the heatmap functions that lets you pass in a range. Right now I think you can specify a palette, but the range is auto-calculated, which is a bit limiting.

I've been tried to change the palette unsuccessfully, e.g. [https://stackoverflow.com/questions/48668965/how-to-change-the-color-palette-of-a-plot-using-r-and-par-command](url).

I'd like to know how can I change the color palette?

`sim_folder <- run_example_sim(verbose = FALSE)`
`nc_file <- file.path(sim_folder, 'output.nc')`
`plot_temp(file = nc_file, fig_path = FALSE)`
`plot_temp(file = nc_file, fig_path = 'test_figure.png', height = 3, reference = 'surface'`

I like the terrain.colors palett or heat.color

**Comment by lawinslow** [comment]
@dvalenciaca Try the current development version. I just pushed some changes that exposes the palette option on `plot_var`. There is an example of an alternative palette in the examples for that function. 

`devtools::install_github('USGS-R/glmtools')

**Comment by jread-usgs** [comment]
@hdugan are you closing these issues because there is a solution in place or because they are `wontfix`?

**Comment by hdugan** [comment]
Closing it because Luke had fixed it, and because my new code also allows custom color palettes.

**Comment by jread-usgs** [comment]
Ok - and Luke's dev version is in the master of this repo? It is good that your code addresses it, but it might be preferable to close the issue when the code is in master instead of a fork or branch.

**Comment by hdugan** [comment]
I thought it was in the master. 
There's a palette argument in plot_var
https://github.com/USGS-R/glmtools/blob/master/R/plot_var.R

**Comment by jread-usgs** [comment]
good deal :+1:
