### ISSUE TITLE
Neverending run_glm

### ISSUE THREAD

**Issue by Taynarafernandes42** [USGS-R/glmtools#242]
Hello. I'm having trouble running GLM, the simulation just go on and on and does not end, could someone please help me to check if it's something wrong with my data?

[GLM data.zip](https://github.com/USGS-R/glmtools/files/2091723/GLM.data.zip)

![image](https://user-images.githubusercontent.com/40183251/41256488-1ec55cf4-6da0-11e8-8d3f-d676f03fd920.png)

**Comment by jread-usgs** [comment]
Hi @Taynarafernandes42 I think this is a GLM question, not a glmtools question, so pointing you to https://groups.google.com/forum/#!categories/aquaticmodelling/glm which I think already has a post w/ this question. 

Please do re-open this issue if there is something connected to glmtools
