### ISSUE TITLE
Additional heatmap plotting method that accepts an appropriately formatted data.frame

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/glmtools#244]
```r
plot_temp(file = "output.nc", fig_path = FALSE, reference = "surface",
  col_lim, ...)
```
but we sometimes want to use the plotting functions w/o using the .nc file as the input.

**Comment by wdwatkins** [comment]
What do you mean by appropriate @jread-usgs? For neural net output, it would be useful to accept long-format data (as opposed to short format that comes out of `get_temp`)

**Comment by jread-usgs** [comment]
Easier to support the short format (each column is a depth), since sparse data that can appear in long format would require different treatment to plot.

**Comment by jread-usgs** [comment]
But now that I think about it, `plot_temp_compare` accepts long format data for field observations

**Comment by jread-usgs** [comment]
The way to do this now w/ the plotting updates is `glmtools::plot_var_df()`
