### ISSUE TITLE
Using output from Lake Analyzer - Center of Buoyancy

### ISSUE THREAD

**Issue by dzrobert** [USGS-R/glmtools#252]
I am trying to get the Center of Buoyancy from Lake Analyzer using the compare_to_field function and the validate_sim function.  

I get the following error: Error in if (depths[2] - depths[1] < 0) { : 
  missing value where TRUE/FALSE needed

This is weird because it works just fine for any other output from Lake Analyzer.

Any suggestions

**Comment by hdugan** [comment]
It's unclear, but your wtr (water temperature output) doesn't have the depths in the correct order. 

The function works using the test file from glmtools
```
install_github('USGS-R/glmtools',ref = 'ggplot_overhaul')
library(glmtools)
nc_file <- system.file("extdata", "output.nc", package = "glmtools")
field_file <- system.file("extdata", "LakeMendota_field_data.csv", package = "glmtools")

compare_to_field(nc_file, field_file, metric = 'center.buoyancy', as_value = TRUE)
```

**Comment by dzrobert** [comment]
Sorry... I screwed up.  My validation data had some data with only surface temperatures.  So, it works fine.  You can close this.
