### ISSUE TITLE
plot_temp doesn't pass fig_path param to plot_var

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/glmtools#257]
Small issue and probably an easy fix, but seems like `fig_path` doesn't get passed to `plot_var` when the user calls `plot_temp`. Instead you get a plot in R. I know we are deprecating `plot_temp`, but until we do, maybe we make this fix?

**Comment by hdugan** [comment]
Fixed on my fork, and will be in next PR

**Comment by jread-usgs** [comment]
@hdugan was this fixed w/ the recent merge?

**Comment by hdugan** [comment]
yes
